#!/usr/bin/env python
# @author: pydo
# @license: MIT
# python -m gif_creator
from gif_creator import run
import os

if __name__ == '__main__':
    default_config = os.path.join(os.getenv('HOME'), 'config.ini.default')
    real_config = os.path.join(os.getenv('HOME'), '.gif_creator.config.ini')

    if os.path.exists(default_config) and not os.path.exists(real_config):
        os.system(f'mv {default_config} {real_config}')

    run(real_config)
